background_opacity: 0.92
colors:
  bright:
    black: '0x555555'
    blue: '0xcaa9fa'
    cyan: '0x8be9fd'
    green: '0x50fa7b'
    magenta: '0xff79c6'
    red: '0xff5555'
    white: '0xffffff'
    yellow: '0xf1fa8c'
  normal:
    black: '0x000000'
    blue: '0xbd93f9'
    cyan: '0x8be9fd'
    green: '0x50fa7b'
    magenta: '0xff79c6'
    red: '0xff5555'
    white: '0xbbbbbb'
    yellow: '0xf1fa8c'
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
draw_bold_text_with_bright_colors: true
font:
  normal:
    family: Source Code Pro
    style: Medium
  size: 13.0
window:
  decorations: none
  dimensions:
    columns: 700
    lines: 600
  padding:
    x: 6
    y: 6
  startup_mode: Maximized
  title: alacritty
